name: shopping_list_test
description: Test CRUD Shopping List

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  fluentui_system_icons: ^1.1.184

  get: ^4.6.5
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.3.2
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  image_path: "assets/icons/ic_launcher.png"